### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by wichtounet** [StreakyCobra/aur-budgetwarrior#2]
Hi :)

I just released the version 1.0 (with a web interface ;) )

There is a dependency to openssl now (libssl and libcrypto).

If you could update it, that would be great :)

Thanks

**Comment by StreakyCobra** [comment]
Hi, thanks ;) Fixed in 8be6d7c6f2936b58177b43e474f0aa73ef6da9cf and updated to [AUR](https://aur.archlinux.org/packages/budgetwarrior/).

**Comment by wichtounet** [comment]
Great :)

Thanks
